# Importing Libraries

In [289]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# CROSS-VALIDATION library(train test Split library)
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score,mean_squared_error, mean_absolute_error

import pickle

# removing the warning
import warnings
warnings.filterwarnings('ignore')

# Initializing Label Encoder

In [290]:
le = LabelEncoder()

# Reading Dataset

In [291]:
df = pd.read_csv("Bus Fare.csv")
df.head()

            Bus Name   Passanger Age  Distance Travel(km)  Bus fare
0              V.I.P              17                   22        30
1             Bolaka              34                   25        60
2  Gajipur Poribohon              19                   32        75
3             United              23                   30        80
4             Bolaka              17                   17        20

Making copy to work on the copied dataset.

In [292]:
df1 = df.copy()

# Initial Analysis

In [293]:
df1.isna().sum()

Bus Name               0
 Passanger Age         0
Distance Travel(km)    0
Bus fare               0
dtype: int64

In [294]:
df1.duplicated().sum()

np.int64(0)

In [295]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Bus Name             24 non-null     str
 1    Passanger Age       24 non-null     int64
 2   Distance Travel(km)  24 non-null     int64
 3   Bus fare             24 non-null     int64
dtypes: int64(3), str(1)
memory usage: 900.0 bytes

# Encoding a column

In [296]:
df1['Bus_Name_Encoded'] = le.fit_transform(df1['Bus Name'])

In [297]:
df1.head()

,Bus Name,Passanger Age,Distance Travel(km),Bus fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1
3,United,23,30,80,4
4,Bolaka,17,17,20,0

# Renaming The columns

In [298]:
df1 = df1.rename(columns={"Bus Name":"Bus_Name", "Passenger Age":"Passenger_Age", "Distance Travel(km)":"Distance_Travelled", "Bus fare":"Bus_Fare"})

In [299]:
df1.head()

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1
3,United,23,30,80,4
4,Bolaka,17,17,20,0

In [300]:
df1 = df1.rename(columns={"Bus_Name_Encoded":"Bus_Name_Encoded", "Passenger_Age":"Passenger_Age", "Distance_Travelled":"Distance_Travelled", "Bus_Fare":"Bus_Fare"})

In [301]:
df1.head()

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1
3,United,23,30,80,4
4,Bolaka,17,17,20,0

# Separating the dataset

In [302]:
df1.columns

Index(['Bus_Name', ' Passanger Age', 'Distance_Travelled', 'Bus_Fare',
       'Bus_Name_Encoded'],
      dtype='str')

In [303]:
x =df1[["Bus_Name_Encoded", " Passanger Age", "Distance_Travelled"]]
y = df1[["Bus_Fare"]]

# Split dataset for training-testing

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = .2, random_state = 45)

In [305]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((19, 3), (5, 3), (19, 1), (5, 1))

# Model Train

In [306]:
lr = LinearRegression()

In [307]:
model = lr.fit(xtrain, ytrain)

R2 score for train data

In [308]:
model.score(xtrain, ytrain)

0.5579939292093279

Check Test Result

In [309]:
model.score(xtest, ytest)

0.7685936679239709

In [310]:
df1.head(3)

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1

# Checking Prediction

In [311]:
model.predict([[5, 25, 50]])

array([[107.64702557]])

# Evaluate the Model

In [312]:
y_pred = model.predict(xtest)
y_pred

array([[25.39359764],
       [58.0322778 ],
       [31.78144658],
       [57.77375284],
       [80.69024218]])

In [313]:
ytest

    Bus_Fare
16        35
20        80
13        20
10        60
17        90

In [314]:
df1['error'] = ytest - y_pred

In [315]:
y_Fair = model.predict(x)

In [316]:
df1['error_total'] = y - y_Fair

In [317]:
df1.head(10)

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded,error,error_total
0,V.I.P,17,22,30,5,NaN,-15.916433
1,Bolaka,34,25,60,0,NaN,-2.572349
2,Gajipur Poribohon,19,32,75,1,NaN,10.384720
3,United,23,30,80,4,NaN,14.036454
4,Bolaka,17,17,20,0,NaN,-12.774484
5,Gajipur Poribohon,40,24,60,1,NaN,-6.222337
6,V.I.P,27,16,45,5,NaN,2.630335
7,Tawqa,18,15,45,3,NaN,13.356585
8,Provati,33,27,60,2,NaN,-7.002683
9,V.I.P,22,40,90,5,NaN,4.517678

In [318]:
df1.drop(['error'], axis=1)

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded,error_total
0,V.I.P,17,22,30,5,-15.916433
1,Bolaka,34,25,60,0,-2.572349
2,Gajipur Poribohon,19,32,75,1,10.384720
3,United,23,30,80,4,14.036454
4,Bolaka,17,17,20,0,-12.774484
5,Gajipur Poribohon,40,24,60,1,-6.222337
6,V.I.P,27,16,45,5,2.630335
7,Tawqa,18,15,45,3,13.356585
8,Provati,33,27,60,2,-7.002683
9,V.I.P,22,40,90,5,4.517678
10,United,25,25,60,4,2.226247
11,Provati,18,40,100,2,19.803018
12,Tawqa,15,24,60,3,13.119090
13,Gajipur Poribohon,15,17,20,1,-11.781447
14,Bolaka,18,32,80,0,16.871018
15,V.I.P,14,35,40,5,-29.028075
16,Provati,16,13,35,2,9.606402
17,United,17,40,90,4,9.309758
18,Tawqa,34,16,45,3,-1.835077
19,Bolaka,15,36,40,0,-28.523793
20,Provati,15,30,80,2,21.967722
21,Tawqa,17,28,60,3,3.592052
22,Gajipur Poribohon,30,32,75,1,1.293822
23,United,15,18,40,4,4.270458

In [319]:
r_score = r2_score(ytest, y_pred)
r_score

0.7685936679239709

In [320]:
# pred with user input
bus_name_encoded = float(input("Enter Bus Name Encoded value: "))
passanger_age = float(input("Enter Passanger Age: "))
distance_travelled = float(input("Enter Distance Travelled: "))

test_data = [[bus_name_encoded, passanger_age, distance_travelled]]
prediction = model.predict(test_data)

print(f"Predicted Bus Fare: {prediction[0][0]}")

Predicted Bus Fare: 43.965434692981866

# Cost of the Model

In [321]:
# cost of the model
mse = mean_squared_error(ytest, y_pred)
mse

161.0588071249163

# Model Saving

In [322]:
pickle.dump(model, open("bus_fare_model.pkl", "wb"))