In [3]:
import pandas as pd

In [4]:
dic = {
  "name" : ["rajib", "kawser", "toha", "chwa"] ,
  "age" :[15, 16, 14, 13],
  "id" : [191, 192, 195, 196],
  "gpa" : [9.83, 9.39, 2.58, 5.23]
}

df1 = pd.DataFrame(dic)
df1

     name  age   id   gpa
0   rajib   15  191  9.83
1  kawser   16  192  9.39
2    toha   14  195  2.58
3    chwa   13  196  5.23

In [5]:
import pandas as pd

dic1 = {
  "name" : ["rajib", "kawser", "toha", "chwa"] ,
  "profession" :[15, 16, 14, 13],
  "id" : [191, 192, 195, 196],
  "due" : [9000, 9300, 2580, 5230]
}

df2 = pd.DataFrame(dic1)
df2

     name  profession   id   due
0   rajib          15  191  9000
1  kawser          16  192  9300
2    toha          14  195  2580
3    chwa          13  196  5230

In [6]:
df2 = df2.drop(["name"], axis = 1)
df2

   profession   id   due
0          15  191  9000
1          16  192  9300
2          14  195  2580
3          13  196  5230

In [7]:
new_df = pd.merge(df1, df2, on = "id", how="inner")
new_df

     name  age   id   gpa  profession   due
0   rajib   15  191  9.83          15  9000
1  kawser   16  192  9.39          16  9300
2    toha   14  195  2.58          14  2580
3    chwa   13  196  5.23          13  5230

In [8]:
df1

     name  age   id   gpa
0   rajib   15  191  9.83
1  kawser   16  192  9.39
2    toha   14  195  2.58
3    chwa   13  196  5.23

In [9]:
import pandas as pd

dic2 = {
  "profession" :["teacher", "worker", "doctor", "engineer"],
  "id" : [191, 192, 197, 198],
  "due" : [9000, 9300, 2580, 5230]
}

df3 = pd.DataFrame(dic2)
df3

  profession   id   due
0    teacher  191  9000
1     worker  192  9300
2     doctor  197  2580
3   engineer  198  5230

In [10]:
new_df1 = pd.merge(df1, df3) # default inner join
new_df1

     name  age   id   gpa profession   due
0   rajib   15  191  9.83    teacher  9000
1  kawser   16  192  9.39     worker  9300

In [11]:
new_df1 = pd.merge(df1, df3, how="left") # left join
new_df1

     name  age   id   gpa profession     due
0   rajib   15  191  9.83    teacher  9000.0
1  kawser   16  192  9.39     worker  9300.0
2    toha   14  195  2.58        NaN     NaN
3    chwa   13  196  5.23        NaN     NaN

In [12]:
new_df1 = pd.merge(df1, df3, how="right") # right join
new_df1

     name   age   id   gpa profession   due
0   rajib  15.0  191  9.83    teacher  9000
1  kawser  16.0  192  9.39     worker  9300
2     NaN   NaN  197   NaN     doctor  2580
3     NaN   NaN  198   NaN   engineer  5230

#using "and" and "or"

In [13]:
new_df1["age"] == 15

0     True
1    False
2    False
3    False
Name: age, dtype: bool

In [14]:
new_df1[new_df1['age']==15]

    name   age   id   gpa profession   due
0  rajib  15.0  191  9.83    teacher  9000

In [15]:
new_df1[new_df1['age']!=15]

     name   age   id   gpa profession   due
1  kawser  16.0  192  9.39     worker  9300
2     NaN   NaN  197   NaN     doctor  2580
3     NaN   NaN  198   NaN   engineer  5230

In [16]:
new_df1[(new_df1["age"]>15) & (new_df1["due"]>9000)]

     name   age   id   gpa profession   due
1  kawser  16.0  192  9.39     worker  9300

In [17]:
new_df1[(new_df1["age"]>15) | (new_df1["due"]>=9000)]

     name   age   id   gpa profession   due
0   rajib  15.0  191  9.83    teacher  9000
1  kawser  16.0  192  9.39     worker  9300

In [18]:
new_df1['profession']

0     teacher
1      worker
2      doctor
3    engineer
Name: profession, dtype: object

In [19]:
new_df1[["profession", "due"]]

  profession   due
0    teacher  9000
1     worker  9300
2     doctor  2580
3   engineer  5230

In [20]:
new_df1[(new_df1["age"]>15) | (new_df1["due"]>=9000)]["profession"]

0    teacher
1     worker
Name: profession, dtype: object

In [21]:
new_df1.to_csv("output.csv", index=False, encoding='utf-8')

In [22]:
df = pd.read_csv('output.csv')
df

     name   age   id   gpa profession   due
0   rajib  15.0  191  9.83    teacher  9000
1  kawser  16.0  192  9.39     worker  9300
2     NaN   NaN  197   NaN     doctor  2580
3     NaN   NaN  198   NaN   engineer  5230

In [23]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
df.to_excel('data.xlsx', index=False)

In [25]:
df = pd.read_csv(r"C:\Users\User\Downloads\archive\SuperMarket Analysis.csv")
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [26]:
df = pd.read_csv("C:/Users/User/Downloads/archive/SuperMarket Analysis.csv")
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [27]:
# github