In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# CROSS-VALIDATION library(train test Split library)
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score,mean_squared_error, mean_absolute_error

import pickle

# removing the warning
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("Bus Fare.csv")

In [4]:
df.head()

            Bus Name   Passanger Age  Distance Travel(km)  Bus fare
0              V.I.P              17                   22        30
1             Bolaka              34                   25        60
2  Gajipur Poribohon              19                   32        75
3             United              23                   30        80
4             Bolaka              17                   17        20

In [5]:
df.columns

Index(['Bus Name', ' Passanger Age', 'Distance Travel(km)', 'Bus fare'], dtype='str')

In [6]:
df = df.rename(columns={"Bus Name": "B_Name", ' Passanger Age': 'P_Age', 'Distance Travel(km)' : 'distance', 'Bus fare' : 'fare'})

In [7]:
df.head()

              B_Name  P_Age  distance  fare
0              V.I.P     17        22    30
1             Bolaka     34        25    60
2  Gajipur Poribohon     19        32    75
3             United     23        30    80
4             Bolaka     17        17    20

In [8]:
df.shape

(24, 4)

In [11]:
# Seperating the independent and dependent variable
# x = df.iloc[:, 0:-1] -> all the rows and all the columns except the last column
x = df.iloc[:, 0:-1]
# y = df.iloc[:, -1] -> all the rows and only the last column
y = df.iloc[:, -1]

In [14]:
# Label Encoding the categorical variable
le = LabelEncoder()
x['B_Name'] = le.fit_transform(df['B_Name'])

In [ ]:
# xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.1, random_state=22)

In [ ]:
#lr =LinearRegression()

In [ ]:
#model = lr.fit(xtrain, ytrain)

In [ ]:
#model.score(xtrain, ytrain)

0.5434072635317042

In [24]:
for i in range (115, 20):
  xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.1, random_state=i)
  lr =LinearRegression()
  model = lr.fit(xtrain, ytrain)
  print(model.score(xtrain, ytrain))

In [ ]:
# test
bus = input