# Class Assignment

** What to Do **
```
1. Data Load.
2. Cleaning.
3. Preprocess (Manual + Loop) with Documentation
```

*** Specifications ***
```
1. Encoding -> manual
2. Ordinal -> manual + loop
3. One Hot Encoding -> use default library
4. Scaling -> All 5 manually. Only one in loop.
```

Importing Necessary Libraries to begin preprocessing.

In [1]:
# Importing necessary libraries for data manipulation and preprocessing
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, MinMaxScaler
from pandas.api.types import is_numeric_dtype

# Creating objects for encoding and scaling
le = LabelEncoder()
ohe = OneHotEncoder(sparse_output=False)
encoder = OrdinalEncoder()
scaler = MinMaxScaler()

Importing dataset to "df"

In [2]:
df = pd.read_excel('synthetic_health_dataset.xlsx')
df.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes

Checking information of the dataset.

In [3]:
# Overall information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               988 non-null    str
 1   Smoking              993 non-null    str
 2   Alcohol_Consumption  649 non-null    str
 3   Exercise_Frequency   993 non-null    str
 4   Blood_Pressure       990 non-null    str
 5   Cholesterol_Level    993 non-null    str
 6   Stress_Level         995 non-null    str
 7   Age                  992 non-null    float64
 8   BMI                  994 non-null    float64
 9   Heart_Rate           992 non-null    float64
 10  Sleep_Hours          994 non-null    float64
 11  Blood_Sugar_Level    997 non-null    float64
 12  Medication_Use       655 non-null    str
 13  Family_History       995 non-null    str
 14  Illness              1000 non-null   str
dtypes: float64(5), str(10)
memory usage: 117.3 KB

In [4]:
# checking all the columns in the dataset
df.columns

Index(['Gender', 'Smoking', 'Alcohol_Consumption', 'Exercise_Frequency',
       'Blood_Pressure', 'Cholesterol_Level', 'Stress_Level', 'Age', 'BMI',
       'Heart_Rate', 'Sleep_Hours', 'Blood_Sugar_Level', 'Medication_Use',
       'Family_History', 'Illness'],
      dtype='str')

In [5]:
# checking for missing values in the dataset
df.isnull().sum()

Gender                  12
Smoking                  7
Alcohol_Consumption    351
Exercise_Frequency       7
Blood_Pressure          10
Cholesterol_Level        7
Stress_Level             5
Age                      8
BMI                      6
Heart_Rate               8
Sleep_Hours              6
Blood_Sugar_Level        3
Medication_Use         345
Family_History           5
Illness                  0
dtype: int64

In [6]:
# checking for duplicate values in the dataset
df.duplicated().sum()

np.int64(0)

# Creating copies.
creating copies to prevent accidental changes of the main dataset.

In [7]:
df1= df.copy()
df2= df.copy()
df3= df.copy()
df4= df.copy()
df5= df.copy()
df6= df.copy()
df7= df.copy()
df8= df.copy()

In [8]:
df1.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes

# Label Encoding

In [9]:
# Label Encoding for Smoking column (manually)
df1["Smoking"] = le.fit_transform(df1["Smoking"])
df1.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,0,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes
1,Other,1,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No
2,Male,1,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes
3,Male,1,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes
4,Male,0,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes

In [10]:
# Checking unique values  of stress level column
df1["Stress_Level"].unique()

<StringArray>
['High', 'Low', 'Medium', nan]
Length: 4, dtype: str

In [11]:
df1['Stress_Level'].value_counts()

Stress_Level
High      346
Medium    328
Low       321
Name: count, dtype: int64

# Ordinal Encoding

In [12]:
# using manual approach by replace method.
df1["Stress_Level"]= df1["Stress_Level"].replace(["Low","Medium","High"],[1,2,3])
df1.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,0,Moderate,Never,Normal,Borderline,3,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes
1,Other,1,NaN,Never,Normal,Normal,1,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No
2,Male,1,Heavy,Daily,High,High,1,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes
3,Male,1,Heavy,Daily,Normal,High,1,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes
4,Male,0,Moderate,Often,High,High,2,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes

In [13]:
# using loop approach for ordinal encoding

colForEncode = ["Cholesterol_Level","Exercise_Frequency","Sleep_Hours"]

for col in colForEncode:
  df1[col + '_Encoded'] = encoder.fit_transform(df1[[col]])

df1.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Cholesterol_Level_Encoded,Exercise_Frequency_Encoded,Sleep_Hours_Encoded
0,Female,0,Moderate,Never,Normal,Borderline,3,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.0,1.0,6.0
1,Other,1,NaN,Never,Normal,Normal,1,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,2.0,1.0,69.0
2,Male,1,Heavy,Daily,High,High,1,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,1.0,0.0,55.0
3,Male,1,Heavy,Daily,Normal,High,1,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,1.0,0.0,65.0
4,Male,0,Moderate,Often,High,High,2,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,1.0,2.0,14.0

# One Hot Encoding

In [14]:
# using the "df2" copied dataframe for one hot encoding.
df3.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes

In [15]:
# Manual one-hot encoding for Cholesterol_Level
df3['Cholesterol_Level_Low'] = (df3['Cholesterol_Level'] == 'Low').astype(int)
df3['Cholesterol_Level_Medium'] = (df3['Cholesterol_Level'] == 'Medium').astype(int)
df3['Cholesterol_Level_High'] = (df3['Cholesterol_Level'] == 'High').astype(int)
df3['Cholesterol_Level_Borderline'] = (df3['Cholesterol_Level'] == 'Borderline').astype(int)

# Drop the original column
df3 = df3.drop('Cholesterol_Level', axis=1)

# View the result
df3.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Cholesterol_Level_Low,Cholesterol_Level_Medium,Cholesterol_Level_High,Cholesterol_Level_Borderline
0,Female,No,Moderate,Never,Normal,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0,0,0,1
1,Other,Yes,NaN,Never,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0,0,0,0
2,Male,Yes,Heavy,Daily,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0,0,1,0
3,Male,Yes,Heavy,Daily,Normal,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0,0,1,0
4,Male,No,Moderate,Often,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0,0,1,0

In [16]:
# One hot encoding using loop
colForOHE = ["Exercise_Frequency","Sleep_Hours"]

for col in colForOHE:
  # Fit and transform the column using OneHotEncoder
  encoded_data = ohe.fit_transform(df3[[col]])
  
  # Get the feature names for the encoded columns
  feature_names = ohe.get_feature_names_out([col])
  
  # Create a DataFrame for the encoded data with the same index as df3
  encoded_df = pd.DataFrame(encoded_data, columns=feature_names, index=df3.index)
  df3 = pd.concat([df3, encoded_df], axis=1)
  
# Drop the original columns
df3 = df3.drop(colForOHE, axis=1)

df3.head()

,Gender,Smoking,Alcohol_Consumption,Blood_Pressure,Stress_Level,Age,BMI,Heart_Rate,Blood_Sugar_Level,Medication_Use,...,Sleep_Hours_9.2,Sleep_Hours_9.3,Sleep_Hours_9.4,Sleep_Hours_9.5,Sleep_Hours_9.6,Sleep_Hours_9.7,Sleep_Hours_9.8,Sleep_Hours_9.9,Sleep_Hours_10.0,Sleep_Hours_nan
0,Female,No,Moderate,Normal,High,90.0,16.6,119.0,143.6,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Other,Yes,NaN,Normal,Low,20.0,29.9,69.0,121.8,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Male,Yes,Heavy,High,Low,52.0,33.5,54.0,107.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Male,Yes,Heavy,Normal,Low,15.0,20.3,72.0,92.1,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Male,No,Moderate,High,Medium,60.0,36.0,58.0,113.6,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Min Max scaler

In [ ]:
# manual approach for min-max scaling
# electing column that are needed to be scaled
col_name = 'Blood_Sugar_Level'

# getting min and max value of the column
min_value = df4[col_name].min()
max_value = df4[col_name].max()

* The formula of Min Max Scaling: 

$$X_{new} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

In [22]:
# Applying the min-max scaling formula to the column
df4[col_name + '_Scaled'] = (df4[col_name] - min_value) / (max_value - min_value)
df4.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Blood_Sugar_Level_Scaled
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.565485
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0.397535
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0.283513
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0.168721
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0.334361

In [24]:
# checking the results of scaling
print(df4[[col_name, col_name + '_Scaled']].head())
print("Min:", df4[col_name + '_Scaled'].min())
print("Max:", df4[col_name + '_Scaled'].max())

   Blood_Sugar_Level  Blood_Sugar_Level_Scaled
0              143.6                  0.565485
1              121.8                  0.397535
2              107.0                  0.283513
3               92.1                  0.168721
4              113.6                  0.334361
Min: 0.0
Max: 1.0

In [25]:
# manual approach for min-max scaling
# electing column that are needed to be scaled
col_name = 'BMI'

# getting min and max value of the column
min_value = df4[col_name].min()
max_value = df4[col_name].max()

In [26]:
# Applying the min-max scaling formula to the column
df4[col_name + '_Scaled'] = (df4[col_name] - min_value) / (max_value - min_value)
df4.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Blood_Sugar_Level_Scaled,BMI_Scaled
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.565485,0.060241
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0.397535,0.594378
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0.283513,0.738956
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0.168721,0.208835
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0.334361,0.839357

In [27]:
# checking the results of scaling
print(df4[[col_name, col_name + '_Scaled']].head())
print("Min:", df4[col_name + '_Scaled'].min())
print("Max:", df4[col_name + '_Scaled'].max())

    BMI  BMI_Scaled
0  16.6    0.060241
1  29.9    0.594378
2  33.5    0.738956
3  20.3    0.208835
4  36.0    0.839357
Min: 0.0
Max: 1.0

In [29]:
# manual approach for min-max scaling
# electing column that are needed to be scaled
col_name = 'Heart_Rate'

# getting min and max value of the column
min_value = df4[col_name].min()
max_value = df4[col_name].max()

In [30]:
# Applying the min-max scaling formula to the column
df4[col_name + '_Scaled'] = (df4[col_name] - min_value) / (max_value - min_value)
df4.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Blood_Sugar_Level_Scaled,BMI_Scaled,Heart_Rate_Scaled
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.565485,0.060241,1.000000
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0.397535,0.594378,0.275362
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0.283513,0.738956,0.057971
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0.168721,0.208835,0.318841
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0.334361,0.839357,0.115942

In [31]:
# checking the results of scaling
print(df4[[col_name, col_name + '_Scaled']].head())
print("Min:", df4[col_name + '_Scaled'].min())
print("Max:", df4[col_name + '_Scaled'].max())

   Heart_Rate  Heart_Rate_Scaled
0       119.0           1.000000
1        69.0           0.275362
2        54.0           0.057971
3        72.0           0.318841
4        58.0           0.115942
Min: 0.0
Max: 1.0

In [32]:
# manual approach for min-max scaling
# electing column that are needed to be scaled
col_name = 'Sleep_Hours'

# getting min and max value of the column
min_value = df4[col_name].min()
max_value = df4[col_name].max()

In [33]:
# Applying the min-max scaling formula to the column
df4[col_name + '_Scaled'] = (df4[col_name] - min_value) / (max_value - min_value)
df4.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Blood_Sugar_Level_Scaled,BMI_Scaled,Heart_Rate_Scaled,Sleep_Hours_Scaled
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.565485,0.060241,1.000000,0.085714
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0.397535,0.594378,0.275362,0.985714
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0.283513,0.738956,0.057971,0.785714
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0.168721,0.208835,0.318841,0.928571
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0.334361,0.839357,0.115942,0.200000

In [34]:
# checking the results of scaling
print(df4[[col_name, col_name + '_Scaled']].head())
print("Min:", df4[col_name + '_Scaled'].min())
print("Max:", df4[col_name + '_Scaled'].max())

   Sleep_Hours  Sleep_Hours_Scaled
0          3.6            0.085714
1          9.9            0.985714
2          8.5            0.785714
3          9.5            0.928571
4          4.4            0.200000
Min: 0.0
Max: 1.0

In [35]:
# manual approach for min-max scaling
# electing column that are needed to be scaled
col_name = 'Age'

# getting min and max value of the column
min_value = df4[col_name].min()
max_value = df4[col_name].max()

In [36]:
# Applying the min-max scaling formula to the column
df4[col_name + '_Scaled'] = (df4[col_name] - min_value) / (max_value - min_value)
df4.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Blood_Sugar_Level_Scaled,BMI_Scaled,Heart_Rate_Scaled,Sleep_Hours_Scaled,Age_Scaled
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.565485,0.060241,1.000000,0.085714,0.909091
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0.397535,0.594378,0.275362,0.985714,0.202020
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0.283513,0.738956,0.057971,0.785714,0.525253
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0.168721,0.208835,0.318841,0.928571,0.151515
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0.334361,0.839357,0.115942,0.200000,0.606061

In [37]:
# checking the results of scaling
print(df4[[col_name, col_name + '_Scaled']].head())
print("Min:", df4[col_name + '_Scaled'].min())
print("Max:", df4[col_name + '_Scaled'].max())

    Age  Age_Scaled
0  90.0    0.909091
1  20.0    0.202020
2  52.0    0.525253
3  15.0    0.151515
4  60.0    0.606061
Min: 0.0
Max: 1.0

In [ ]:
#  using loop for min-max scaling
df_loop = df5

# loop starts here
for col in df_loop.columns:
  # checking if the column is numeric before applying min-max scaling
    if is_numeric_dtype(df_loop[col]):
      # getting min and max value of the column
        min_value = df_loop[col].min()
        max_value = df_loop[col].max()
        
        # Applying the min-max scaling formula to the column
        df_loop[col + '_Scaled'] = (df_loop[col] - min_value) / (max_value - min_value)

# checking the results of scaling for the first few columns
df_loop.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,Age_Scaled,BMI_Scaled,Heart_Rate_Scaled,Sleep_Hours_Scaled,Blood_Sugar_Level_Scaled
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes,0.909091,0.060241,1.000000,0.085714,0.565485
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No,0.202020,0.594378,0.275362,0.985714,0.397535
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes,0.525253,0.738956,0.057971,0.785714,0.283513
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes,0.151515,0.208835,0.318841,0.928571,0.168721
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes,0.606061,0.839357,0.115942,0.200000,0.334361