In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from pandas.api.types import is_numeric_dtype

le = LabelEncoder()

In [2]:
df = pd.read_csv('insurance.csv')

.head() -> displays first 5 values by default.

In [3]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

.tail() -> displays last 5 values by default.

In [4]:
df.tail()

      age     sex   bmi  children smoker     region  expenses
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

.info() -> displays description of the dataset.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

.isna() -> method. that will display nan values is present or absent.

In [6]:
df.isna()

        age    sex    bmi  children  smoker  region  expenses
0     False  False  False     False   False   False     False
1     False  False  False     False   False   False     False
2     False  False  False     False   False   False     False
3     False  False  False     False   False   False     False
4     False  False  False     False   False   False     False
...     ...    ...    ...       ...     ...     ...       ...
1333  False  False  False     False   False   False     False
1334  False  False  False     False   False   False     False
1335  False  False  False     False   False   False     False
1336  False  False  False     False   False   False     False
1337  False  False  False     False   False   False     False

[1338 rows x 7 columns]

.isna().sum() -> here sum() method sums up all the nan values in a column and gives the sum of it.

In [7]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

.isnull() -> method that displays nan / null values by true or false.

In [8]:
df.isnull()

        age    sex    bmi  children  smoker  region  expenses
0     False  False  False     False   False   False     False
1     False  False  False     False   False   False     False
2     False  False  False     False   False   False     False
3     False  False  False     False   False   False     False
4     False  False  False     False   False   False     False
...     ...    ...    ...       ...     ...     ...       ...
1333  False  False  False     False   False   False     False
1334  False  False  False     False   False   False     False
1335  False  False  False     False   False   False     False
1336  False  False  False     False   False   False     False
1337  False  False  False     False   False   False     False

[1338 rows x 7 columns]

In [9]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

condition for being duplicate is that a full row's values has to be same.

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [11]:
df.duplicated().sum()

np.int64(1)

.dropna()-> method is used to drop "nan" / "null" value

In [12]:
df.dropna()

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

.drop_duplicates() -> method is used for dropping duplicate values.

In [13]:
df.drop_duplicates()

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1337 rows x 7 columns]

In [14]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [15]:
df['sex'].value_counts()

sex
male      676
female    662
Name: count, dtype: int64

In [16]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()
df6 = df.copy()
df7 = df.copy()
df8 = df.copy()

Label encoding apply

In [17]:
le

LabelEncoder()

To train we use a method called "fit".

In [18]:
encode =le.fit(df["sex"])

In [19]:
encode

LabelEncoder()

In [20]:
df['sex'] = encode.transform(df['sex'])

In [21]:
df.head()

   age  sex   bmi  children smoker     region  expenses
0   19    0  27.9         0    yes  southwest  16884.92
1   18    1  33.8         1     no  southeast   1725.55
2   28    1  33.0         3     no  southeast   4449.46
3   33    1  22.7         0     no  northwest  21984.47
4   32    1  28.9         0     no  northwest   3866.86

In [22]:
df.smoker.value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [23]:
df["smoker"] = le.fit_transform(df["smoker"])

In [24]:
df.head()

   age  sex   bmi  children  smoker     region  expenses
0   19    0  27.9         0       1  southwest  16884.92
1   18    1  33.8         1       0  southeast   1725.55
2   28    1  33.0         3       0  southeast   4449.46
3   33    1  22.7         0       0  northwest  21984.47
4   32    1  28.9         0       0  northwest   3866.86

In [25]:
df1.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

Check a column is numerical or not

In [26]:
df1.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'expenses'], dtype='str')

In [27]:
for col in df1.columns:
  # print(col)
  if is_numeric_dtype(df1[col]):
    continue
  else:
    df1[col ]= le.fit_transform(df1[col])

In [28]:
df1.head()

   age  sex   bmi  children  smoker  region  expenses
0   19    0  27.9         0       1       3  16884.92
1   18    1  33.8         1       0       2   1725.55
2   28    1  33.0         3       0       2   4449.46
3   33    1  22.7         0       0       1  21984.47
4   32    1  28.9         0       0       1   3866.86

In [29]:
df1.region.value_counts()

region
2    364
3    325
1    325
0    324
Name: count, dtype: int64

In [30]:
df2.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

# Replace

In [31]:
df.head()

   age  sex   bmi  children  smoker     region  expenses
0   19    0  27.9         0       1  southwest  16884.92
1   18    1  33.8         1       0  southeast   1725.55
2   28    1  33.0         3       0  southeast   4449.46
3   33    1  22.7         0       0  northwest  21984.47
4   32    1  28.9         0       0  northwest   3866.86

In [32]:
df.region.value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [33]:
df["region"] =df["region"].replace(["southeast", "southwest", "northwest", "northeast"], [1, 2, 3, 4])

In [34]:
df.head()

   age  sex   bmi  children  smoker region  expenses
0   19    0  27.9         0       1      2  16884.92
1   18    1  33.8         1       0      1   1725.55
2   28    1  33.0         3       0      1   4449.46
3   33    1  22.7         0       0      3  21984.47
4   32    1  28.9         0       0      3   3866.86

In [35]:
df.region.value_counts()

region
1    364
2    325
3    325
4    324
Name: count, dtype: int64

In [36]:
df2.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [37]:
df2["sex"].unique().tolist()

['female', 'male']

In [38]:
df2["sex"].nunique()

2

Using loop

In [39]:
for col in df2.columns:
  if is_numeric_dtype(df2[col]):
    continue
  else:
    count = df2[col].nunique()
    cate_list = df2[col].unique().tolist()
    if count == 2:
      df2[col] = df2[col].replace(cate_list, [0, 1])
    elif count == 3:
      df2[col] = df2[col].replace(cate_list, [0, 1, 2])
    elif count == 4:
      df2[col] = df2[col].replace(cate_list, [0, 1, 2, 3])

In [40]:
df2.head()

   age sex   bmi  children smoker region  expenses
0   19   0  27.9         0      0      0  16884.92
1   18   1  33.8         1      1      1   1725.55
2   28   1  33.0         3      1      1   4449.46
3   33   1  22.7         0      1      2  21984.47
4   32   1  28.9         0      1      2   3866.86

In [41]:
# ordinal encoding & target encoding use both manual and loop

# One Hot encoding

In [42]:
df3.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [43]:
# dummy = pd.get_dummies(df3["sex"])

because float it shows true false. thats why transformed int

In [44]:
dummy = pd.get_dummies(df3["sex"]).astype("int64")

In [45]:
dummy

      female  male
0          1     0
1          0     1
2          0     1
3          0     1
4          0     1
...      ...   ...
1333       0     1
1334       1     0
1335       1     0
1336       1     0
1337       1     0

[1338 rows x 2 columns]

In [46]:
df3 = df3.drop(["sex"], axis=1)

In [47]:
df3.head()

   age   bmi  children smoker     region  expenses
0   19  27.9         0    yes  southwest  16884.92
1   18  33.8         1     no  southeast   1725.55
2   28  33.0         3     no  southeast   4449.46
3   33  22.7         0     no  northwest  21984.47
4   32  28.9         0     no  northwest   3866.86

In [48]:
type(dummy)

pandas.DataFrame

In [49]:
new_df3 = pd.concat([df3, dummy], axis = 1)

In [50]:
new_df3

      age   bmi  children smoker     region  expenses  female  male
0      19  27.9         0    yes  southwest  16884.92       1     0
1      18  33.8         1     no  southeast   1725.55       0     1
2      28  33.0         3     no  southeast   4449.46       0     1
3      33  22.7         0     no  northwest  21984.47       0     1
4      32  28.9         0     no  northwest   3866.86       0     1
...   ...   ...       ...    ...        ...       ...     ...   ...
1333   50  31.0         3     no  northwest  10600.55       0     1
1334   18  31.9         0     no  northeast   2205.98       1     0
1335   18  36.9         0     no  southeast   1629.83       1     0
1336   21  25.8         0     no  southwest   2007.95       1     0
1337   61  29.1         0    yes  northwest  29141.36       1     0

[1338 rows x 8 columns]

In [51]:
dummy = pd.get_dummies(new_df3["region"]).astype("int64")

In [52]:
dummy

      northeast  northwest  southeast  southwest
0             0          0          0          1
1             0          0          1          0
2             0          0          1          0
3             0          1          0          0
4             0          1          0          0
...         ...        ...        ...        ...
1333          0          1          0          0
1334          1          0          0          0
1335          0          0          1          0
1336          0          0          0          1
1337          0          1          0          0

[1338 rows x 4 columns]

In [53]:
new_df3= new_df3.drop(["region"], axis=1)

In [54]:
new_df3

      age   bmi  children smoker  expenses  female  male
0      19  27.9         0    yes  16884.92       1     0
1      18  33.8         1     no   1725.55       0     1
2      28  33.0         3     no   4449.46       0     1
3      33  22.7         0     no  21984.47       0     1
4      32  28.9         0     no   3866.86       0     1
...   ...   ...       ...    ...       ...     ...   ...
1333   50  31.0         3     no  10600.55       0     1
1334   18  31.9         0     no   2205.98       1     0
1335   18  36.9         0     no   1629.83       1     0
1336   21  25.8         0     no   2007.95       1     0
1337   61  29.1         0    yes  29141.36       1     0

[1338 rows x 7 columns]

In [55]:
new_df3 = pd.concat([new_df3, dummy], axis = 1)
new_df3

,age,bmi,children,smoker,expenses,female,male,northeast,northwest,southeast,southwest
0,19,27.9,0,yes,16884.92,1,0,0,0,0,1
1,18,33.8,1,no,1725.55,0,1,0,0,1,0
2,28,33.0,3,no,4449.46,0,1,0,0,1,0
3,33,22.7,0,no,21984.47,0,1,0,1,0,0
4,32,28.9,0,no,3866.86,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,31.0,3,no,10600.55,0,1,0,1,0,0
1334,18,31.9,0,no,2205.98,1,0,1,0,0,0
1335,18,36.9,0,no,1629.83,1,0,0,0,1,0
1336,21,25.8,0,no,2007.95,1,0,0,0,0,1
1337,61,29.1,0,yes,29141.36,1,0,0,1,0,0

In [56]:
# do use loop

using library

In [57]:
ohe = OneHotEncoder()

In [58]:
# do by yourself